### ISSUE TITLE
RoR group project: set up your Kanban board

### ISSUE THREAD

**Issue by AntonioHincapie** [AntonioHincapie/recipe_app#9]
- I have to develop this project alone this week.
- [Link to the project](https://github.com/AntonioHincapie/recipe_app/projects/1)

**Comment by youmari** [comment]
# Project Approved :trophy: :tada: 🟢 

Hi @AntonioHincapie 

Your project is complete!  You have done it exceptionally well. it's time to merge it :100: 
Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also connect with me on [slack](https://microverse-students.slack.com/team/U02FTTCCU2V)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).
